/* 
Copyright (c) 2017 Deepak Khanal
All Rights Reserved
dkhanal AT gmail DOT com

View of All Causes of Medical Device Failure 
*/

CREATE VIEW [dbo].[VW_DEVICE_PROBLEM_CODES_CDRH_FDA_COMBINED]
AS
SELECT 
ISNULL(DPC.DEVICE_PROBLEM_CODE, CDRH.[FDA Source Code]) AS DEVICE_PROBLEM_CODE,
ISNULL(DPC.DESCRIPTION, CDRH.[FDA Source PT]) AS DESCRIPTION

FROM DEVICE_PROBLEM_CODES_ORIG DPC
FULL OUTER JOIN [FDA_CDRH_NCIT_SUBSETS_ORIG] CDRH
ON DEVICE_PROBLEM_CODE = [FDA Source Code]
