/* 
Copyright (c) 2017 Deepak Khanal
All Rights Reserved
dkhanal AT gmail DOT com

Computing Technology-related Medical Device Events Associated with Patient Injury
*/

SELECT [YEAR], COUNT(*) AS [COUNT]
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]

WHERE MDR_REPORT_KEY IN (
	SELECT MDR_REPORT_KEY
	FROM [dbo].[PATIENT_THRU_2016_ORIG] 
	WHERE SEQUENCE_NUMBER_OUTCOME LIKE '%H%'
		OR SEQUENCE_NUMBER_OUTCOME LIKE '%L%'
		OR SEQUENCE_NUMBER_OUTCOME LIKE '%S%'

	UNION

	SELECT MDR_REPORT_KEY
	FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
	WHERE EVENT_TYPE IN ('IJ', 'IL', 'IN')
)
GROUP BY [YEAR]
ORDER BY [YEAR]
