/* 
Copyright (c) 2017 Deepak Khanal
All Rights Reserved
dkhanal AT gmail DOT com

Retrieves counts of rows in MAUDE tables after data import. 
*/

SELECT 'DEVICE_PROBLEM_CODES_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[DEVICE_PROBLEM_CODES_ORIG] UNION
SELECT 'FDA_CDRH_NCIT_SUBSETS_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FDA_CDRH_NCIT_SUBSETS_ORIG] UNION
SELECT 'MDR_FOI_THRU_2016_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[MDR_FOI_THRU_2016_ORIG] UNION
SELECT 'MDR_FOI_CHANGE_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[MDR_FOI_CHANGE_ORIG] UNION
SELECT 'FOI_DEV_PROBLEM_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_DEV_PROBLEM_ORIG] UNION
SELECT 'FOI_TEXT_2007_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2007_ORIG] UNION
SELECT 'FOI_TEXT_2008_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2008_ORIG] UNION
SELECT 'FOI_TEXT_2009_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2009_ORIG] UNION
SELECT 'FOI_TEXT_2010_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2010_ORIG] UNION
SELECT 'FOI_TEXT_2011_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2011_ORIG] UNION
SELECT 'FOI_TEXT_2012_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2012_ORIG] UNION
SELECT 'FOI_TEXT_2013_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2013_ORIG] UNION
SELECT 'FOI_TEXT_2014_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2014_ORIG] UNION
SELECT 'FOI_TEXT_2015_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2015_ORIG] UNION
SELECT 'FOI_TEXT_2016_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_2016_ORIG] UNION
SELECT 'FOI_TEXT_CHANGE_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[FOI_TEXT_CHANGE_ORIG] UNION
SELECT 'PATIENT_THRU_2016_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[PATIENT_THRU_2016_ORIG] UNION
SELECT 'PATIENT_CHANGE_ORIG' AS TableName, COUNT(*) AS TotalRecords FROM [dbo].[PATIENT_CHANGE_ORIG] 
