/* 
Copyright (c) 2017 Deepak Khanal
All Rights Reserved
dkhanal AT gmail DOT com

Number of Computing Technology-related Events with Patient Death
*/

SELECT COUNT(DISTINCT MDR_REPORT_KEY)
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
WHERE EVENT_TYPE IN ('D')
GO

SELECT COUNT(DISTINCT MDR_REPORT_KEY)
FROM PATIENT_THRU_2016_ORIG
WHERE SEQUENCE_NUMBER_OUTCOME LIKE '%D%'
AND MDR_REPORT_KEY IN (
	SELECT MDR_REPORT_KEY FROM [VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
)
GO
