/* 
Copyright (c) 2017 Deepak Khanal
All Rights Reserved
dkhanal AT gmail DOT com

Patient-reported Events by Year
*/

SELECT [YEAR], COUNT(*) AS [COUNT]
INTO #TBL_OVERALL
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016]
GROUP BY [YEAR]

SELECT [YEAR], COUNT(*) AS [COUNT]
INTO #TBL_COMPUTING_RELATED
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
GROUP BY [YEAR]

SELECT [YEAR], COUNT(*) AS [COUNT]
INTO #TBL_OVERALL_REPORTED_BY_PATIENTS
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016]
WHERE [REPORTER_OCCUPATION_CODE] IN ('0LP', '305', '306')
GROUP BY [YEAR]

SELECT [YEAR], COUNT(*) AS [COUNT]
INTO #TBL_COMPUTING_RELATED_REPORTED_BY_PATIENTS
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
WHERE [REPORTER_OCCUPATION_CODE] IN ('0LP', '305', '306')
GROUP BY [YEAR]

SELECT
O.[YEAR], 
O.[COUNT] AS TOTAL_REPORTS,
OP.[COUNT] AS OVERALL_PATIENT_REPORTED, 
ROUND((OP.[COUNT] * 100.0)/O.[COUNT], 2) AS PERCENT_OF_OVERALL,
COMPUTING.[COUNT] AS TOTAL_COMPUTING_RELATED_REPORTS,
COMPUTINGP.[COUNT] AS COMPUTING_RELATED_PATIENT_REPORTED,
ROUND((COMPUTINGP.[COUNT] * 100.0)/COMPUTING.[COUNT], 2) AS PERCENT_OF_COMPUTING_RELATED
FROM 
#TBL_OVERALL AS O,
#TBL_COMPUTING_RELATED AS COMPUTING,
#TBL_OVERALL_REPORTED_BY_PATIENTS AS OP, 
#TBL_COMPUTING_RELATED_REPORTED_BY_PATIENTS AS COMPUTINGP
WHERE 
O.[YEAR] = COMPUTING.[YEAR]
AND O.[YEAR] = OP.[YEAR]
AND O.[YEAR] = COMPUTINGP.[YEAR]
ORDER BY [YEAR]
