/* 
Copyright (c) 2017 Deepak Khanal
All Rights Reserved
dkhanal AT gmail DOT com

Yearly number of Events Associated with Patient Death
*/

SELECT [YEAR], COUNT(*) AS [COUNT]
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016]
WHERE MDR_REPORT_KEY IN (
	SELECT MDR_REPORT_KEY
	FROM [dbo].[PATIENT_THRU_2016_ORIG] 
	WHERE SEQUENCE_NUMBER_OUTCOME LIKE '%D%'
	UNION
	SELECT MDR_REPORT_KEY
	FROM [dbo].[VW_MDR_FOI_2007_THRU_2016]
	WHERE EVENT_TYPE IN ('D')
)
GROUP BY [YEAR]
ORDER BY [YEAR]
GO

SELECT [YEAR], COUNT(*) AS [COUNT]
FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
WHERE MDR_REPORT_KEY IN (
	SELECT MDR_REPORT_KEY
	FROM [dbo].[PATIENT_THRU_2016_ORIG] 
	WHERE SEQUENCE_NUMBER_OUTCOME LIKE '%D%'
	UNION
	SELECT MDR_REPORT_KEY
	FROM [dbo].[VW_MDR_FOI_2007_THRU_2016_COMPUTING_CAUSE_ML]
	WHERE EVENT_TYPE IN ('D')
)
GROUP BY [YEAR]
ORDER BY [YEAR]
